### PR TITLE
2.071 updates

### LINKED ISSUE #219: dmd-2.071.0 error in soundbuffer.d
With dmd-2.071.0 I have some errors:

    C:\Users\...\src\dsfml\audio\soundbuffer.d(63,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(148,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(172,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(196,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(222,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundbuffer.d(247,22): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundrecorder.d(61,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundrecorder.d(92,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundstream.d(82,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    C:\Users\...\src\dsfml\audio\soundstream.d(278,21): Error: function object.Object.toString () is not callable using argument types (const(char)*)
    dmd failed with exit code 1.

dmd-2.070.2 works fine

### PR DESCRIPTION
**Pull request by Jebbs**
This let's you use the most recent compiler for DSFML.

Fixes #219

### CODE REVIEW

File: src/dsfml/window/window.d [hunk 1]
```diff
@@ -375,7 +375,7 @@ class Window
 	{
 		import dsfml.system.string;
 		sfWindow_createFromHandle(sfPtr, handle, settings.depthBits,settings.stencilBits, settings.antialiasingLevel, settings.majorVersion, settings.minorVersion);
-		err.write(toString(sfErr_getOutput()));
+		err.write(dsfml.system.string.toString(sfErr_getOutput()));
```
Comment (sigod) [inline src/dsfml/window/window.d]: Why do you need `import dsfml.system.string`?

Comment (Jebbs) [inline src/dsfml/window/window.d]: So that I don't have to import anything from the standard library.

dsfml.system.string.toString is specific to C strings and its only job is to convert them to a D styled string.

Comment (sigod) [inline src/dsfml/window/window.d]: Have you tried to `import dsfml.system.string : toString`? Or do need something else from that module?

Comment (Jebbs) [inline src/dsfml/window/window.d]: That wouldn't help. Based on the new rules, the compiler will attempt to look up symbols locally before checking imported modules, even modules that are imported in the same scope. It will always find Object.toString first, so we have to be explicit.

Does `import module : symbol` only import the one symbol now? I was under the assumption that it still imported the whole module.

File: src/dsfml/graphics/text.d [hunk 2]
```diff
@@ -34,6 +34,8 @@ import dsfml.graphics.primitivetype;
 
 import dsfml.system.vector2;
 
+import std.typecons:Rebindable;
```
Comment (sigod) [inline src/dsfml/graphics/text.d]: Minor styling issue: you should probably place one space after colon (`:`) as you once did in [`dsfml.window.videomode`][0].

[0]: https://github.com/Jebbs/DSFML/blob/72677feeb62c53173ce4d5c2d5d3dca806fed505/src/dsfml/window/videomode.d#L121

Comment (Jebbs) [inline src/dsfml/graphics/text.d]: You're right, but I'm not going to worry about it for this PR.

I'll go ahead and fix it in the 2.3 branch though. All work on DSFML for the time being will take place there.

File: src/dsfml/window/window.d (hunk 1 above)
Comment (sigod) [inline src/dsfml/window/window.d]: > Does `import module : symbol` only import the one symbol now? I was under the assumption that it still imported the whole module.

I was under impression that it always imported only the selected symbols.

Comment (sigod) [inline src/dsfml/window/window.d]: > You still need to import the module. I only explicitly wrote `dsfml.system.string.toString` because otherwise it uses Object.toString which is what broke the code previously.

> It will always find Object.toString first

I'm trying to construct the smallest possible code to reproduce this. But it works either way. Though, I don't use `extern(C)`.

Comment (Jebbs) [inline src/dsfml/window/window.d]: >I was under impression that it always imported only the selected symbols.

As I understand it, the compiler lets you use only those symbols as part of the import system, but it does actually import the entire module.
